added tooltip and fix ticks overlap
raccoongang/acceptor pull request #133
Opened 2018-05-21 13:46 UTC by otecMuxah

[OLGA-33](https://youtrack.raccoongang.com/issue/OLGA-33)
[OLGA-34](https://youtrack.raccoongang.com/issue/OLGA-34)

2018-05-22 10:46 UTC, idegtiarov requested changes
Please improve one typo in the text

2018-05-22 10:46 UTC, idegtiarov commented on web/olga/charts/templates/charts/graphs.html
> +                                        <p class="tooltip-unzoom">To un zoom plot - double click on it</p>
typo s/un zoom/unzoom/

2018-05-23 13:44 UTC, otecMuxah commented on web/olga/charts/templates/charts/graphs.html
> +                                        <p class="tooltip-unzoom">To un zoom plot - double click on it</p>
done

2018-05-24 09:55 UTC, idegtiarov approved these changes

2018-05-24 09:56 UTC, merged